version: '3'

services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.24.x
    container_name: geoserver
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=ysld,h2
      - COMMUNITY_EXTENSIONS=ogcapi-features,ogcapi-images,ogcapi-maps,ogcapi-styles,ogcapi-tiles
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /data:/opt/geoserver_data

